"""
🗄️ CockroachDB Query Tool

This tool lets DeepSeek generate and run SQL queries from your
natural language questions.

Examples of what you can ask:
  - "What tables do I have in my database?"
  - "Show me all calculations from today"
  - "What's the average result of all calculations?"
  - "Describe the schema of the calculations table"

Safety:
  - We ALLOW: SELECT, INSERT, CREATE TABLE, CREATE INDEX, ALTER TABLE
  - We BLOCK: DROP, TRUNCATE, DELETE, UPDATE (without WHERE), DROP DATABASE
  - This gives you flexibility while preventing accidental disasters.
"""

import re
import traceback
import datetime
from decimal import Decimal
import structlog
from .base import BaseTool


logger = structlog.get_logger()


# ── BLOCKED SQL STATEMENTS ─────────────────────────────────────────────
# These patterns are NOT allowed — they're too destructive to run blindly.
BLOCKED_PATTERNS = [
    r"\bDROP\s+(TABLE|DATABASE|SCHEMA|INDEX|VIEW)\b",
    r"\bTRUNCATE\b",
    r"\bDELETE\s+FROM\b",
    r"\bALTER\s+(TABLE|DATABASE|SCHEMA)\s+DROP\b",
    r"\bUPDATE\b",  # Update without WHERE is dangerous; block all for safety
]


def _serialize_value(value):
    """
    Convert database values to JSON-safe types.
    
    datetime, date, time → ISO string
    Decimal → float or string
    bytes → string (decoded)
    Everything else → as-is (int, float, str, None, bool)
    """
    if isinstance(value, (datetime.datetime, datetime.date, datetime.time)):
        return value.isoformat()
    elif isinstance(value, Decimal):
        return float(value)
    elif isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    elif isinstance(value, set):
        return list(value)
    return value


def is_safe_query(sql: str) -> bool:
    """
    Check if the SQL query is safe to execute.

    We allow SELECT, INSERT, CREATE TABLE, ALTER TABLE ADD, etc.
    We block destructive operations like DROP, TRUNCATE, DELETE.
    """
    # Remove comments and normalize whitespace for checking
    cleaned = re.sub(r"--.*$", "", sql, flags=re.MULTILINE).strip().upper()

    # Check against blocked patterns
    for pattern in BLOCKED_PATTERNS:
        if re.search(pattern, cleaned):
            logger.warning("db.query_blocked", sql=sql[:100], pattern=pattern)
            return False
    return True


class DatabaseQueryTool(BaseTool):
    """
    Tool for executing SQL queries against CockroachDB.
    """
    
    def get_name(self) -> str:
        return "query_database"
    
    def get_description(self) -> str:
        return (
            "Run a SQL query against the CockroachDB database. "
            "Use this to discover tables, inspect schemas, fetch data, or insert records. "
            "The database has a 'calculations' table with columns: "
            "id, expression, result, created_at."
        )
    
    def get_parameters(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "sql": {
                    "type": "string",
                    "description": (
                        "The SQL query to execute. "
                        "Allowed: SELECT, INSERT, CREATE TABLE, CREATE INDEX, ALTER TABLE. "
                        "Blocked: DROP, TRUNCATE, DELETE, UPDATE."
                    )
                }
            },
            "required": ["sql"]
        }
    
    def execute(self, db_conn, sql: str) -> dict:
        """
        Execute a SQL query against CockroachDB and return the results.
        
        Args:
            db_conn: Connection to CockroachDB
            sql: The SQL query to run (generated by the LLM from your question)
        
        Returns:
            dict with keys: "success", "columns", "rows", "row_count", "message"
        """
        try:
            # ── 1. SAFETY CHECK ──────────────────────────────────────────
            if not is_safe_query(sql):
                logger.warning("db.query_blocked", sql=sql[:100])
                return {
                    "success": False,
                    "error": (
                        "BLOCKED: This query contains destructive operations "
                        "(DROP, TRUNCATE, DELETE, etc.). "
                        "Only SELECT, INSERT, and CREATE operations are allowed."
                    ),
                    "sql": sql,
                }

            # ── 2. EXECUTE THE QUERY ─────────────────────────────────────
            logger.info("db.query_executing", sql=sql[:100])
            with db_conn.cursor() as cur:
                cur.execute(sql)

                # If the query produced rows (e.g. SELECT), fetch them
                if cur.description:
                    # Get column names from the cursor description
                    columns = [desc[0] for desc in cur.description]
                    # Fetch all rows
                    rows = cur.fetchall()
                    row_count = len(rows)
                    logger.info("db.query_success", row_count=row_count, sql=sql[:100])

                    # Format the results nicely, serializing datetime/Decimal/etc.
                    return {
                        "success": True,
                        "columns": columns,
                        "rows": [[_serialize_value(v) for v in row] for row in rows],
                        "row_count": row_count,
                        "message": (
                            f"Query returned {row_count} row(s)" 
                            if row_count > 0 
                            else "Query returned no rows"
                        ),
                        "sql": sql,
                    }
                else:
                    # No rows returned (e.g. INSERT, CREATE TABLE)
                    # Get the row count affected (if applicable)
                    row_count = cur.rowcount
                    db_conn.commit()
                    logger.info("db.query_success", row_count=row_count, sql=sql[:100])
                    return {
                        "success": True,
                        "columns": [],
                        "rows": [],
                        "row_count": row_count if row_count > 0 else 0,
                        "message": (
                            f"Query executed successfully. {row_count} row(s) affected."
                            if row_count and row_count > 0
                            else "Query executed successfully."
                        ),
                        "sql": sql,
                    }

        except Exception as e:
            # Catch and return SQL errors (wrong syntax, missing tables, etc.)
            logger.error("db.query_failed", sql=sql[:100], error=str(e))
            return {
                "success": False,
                "error": str(e),
                "sql": sql,
                "message": f"SQL error: {e}",
            }


# Export singleton instance for easy import
db_query_tool = DatabaseQueryTool()
